using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LaserLevelManager : LevelManager
{
    double time = 0;
    // Start is called before the first frame update
    protected override void Start()
    {
        base.Start();
        time = 0;
    }

    // Update is called once per frame
    protected override void Update()
    {
        if (Input.GetKey("D"))
        {
            time += Time.deltaTime;
        }
        if (Input.GetKeyUp("D"))
            time = 0;
        if (WinCondition())
            WinMessage();
        base.Update();
    }

    protected override bool WinCondition()
    {
        if (time > 10.0)
            return true;
        else
            return false;
    }

    protected override bool LoseCondition()
    {
        if (base.player.time > 15.0)
            return true;
        else return false;
    }

    protected bool WinMessage()
    {

    }
}
