using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ScreenMovement : MonoBehaviour
{
    public LevelManager Levelmanager;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void FixedUpdate()
    {
        var v = Levelmanager.player.v;
        

        transform.rotation = Quaternion.AngleAxis(Vector3.SignedAngle(v,Levelmanager.player.orientation, Vector3.up), Vector3.forward);
    }
}
