using Assets.Scripts.Interface;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Arm : MonoBehaviour
{

    public IBody body;
    // Start is called before the first frame update
    void Start()
    {
        body = transform.parent.GetComponent<PlayerMovement>();
    }

    private void OnTriggerEnter(Collider other)
    {
        body.OnTriggerEnterArm(other);
    }

    private void OnTriggerExit(Collider other)
    {
        body.OnTriggerExitArm(other);
    }
}
