using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MarkerMovement : Planemovement
{
    Vector3 originalscale;
    new void Start()
    {
        base.Start();
        //Renderer r = theobject.GetComponent<Renderer>();
        //Color materialColor = r.material.color;
        //r.material.color = Color.clear;
        v = new Vector3(0.0f, 0.0f, 0.0f);
        //playergamma = 1.0f;
        orientation = new Vector3(0.0f, 0.0f, 1.0f);
        gamma = 1.0f;
        originalscale = theobject.transform.localScale;
    }

    protected override void FixedUpdate()
    {
        cnt++;
        if (cnt % 480 == 0)
        {
            cnt = 0;
        }
        transform.Translate((float)Constants.c * Vector3.up * Time.fixedDeltaTime * (float)levelManager.player.gamma, Space.World);

        theobject.transform.localScale = originalscale * 0.5f * (Mathf.Cos(2 * Mathf.PI * cnt / 480) + 2);

    }
}
