using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class SelectManager : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void Tutorial1()
    {
        SceneManager.LoadScene("Tutorial1");
    }

    public void Tutorial2()
    {
        SceneManager.LoadScene("Tutorial2");
    }

    public void ClockLevel()
    {
        SceneManager.LoadScene("ClockLevel");
    }

    public void LaserLevel()
    {
        SceneManager.LoadScene("LaserLevel");
    }

}
